version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 590340239150.dkr.ecr.us-east-1.amazonaws.com
      
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      
      # Configurar Python 3.11
      - echo "Configurando Python 3.11..."
      - python3.11 --version
      
      # Instalar Poetry
      - echo "Instalando Poetry..."
      - pip install poetry==2.1.1
      
      # Configurar Poetry para no crear entorno virtual (similar a Dockerfile)
      - poetry config virtualenvs.create false
      
      # Instalar dependencias (incluyendo dev dependencies para tests)
      - echo "Instalando dependencias..."
      - poetry install --with dev
      
      # Verificar instalación
      - poetry --version
      - python --version

  build:
    commands:
      - echo Build started on `date`
      
      # Ejecutar tests con pytest
      - echo "Ejecutando tests..."
      - poetry run pytest src/tests/ -v --tb=short
      
      - echo Building the Docker image...
      - docker build -t blacklist .
      - docker tag blacklist:latest 590340239150.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 590340239150.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"blacklist-app","imageUri":"590340239150.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"590340239150.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest"}' > imageDetail.json
      - cat imagedefinitions.json
      
      # Mostrar información del build
      - echo "Build completado exitosamente"
      - echo "Python version:"
      - python --version
      - echo "Poetry version:"
      - poetry --version

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  base-directory: '.'
  name: blacklist-api-build-$(date +%Y-%m-%d)
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json

reports:
  pytest-reports:
    files:
      - '**/*'
    base-directory: '.'

